name: Artifacts

on:
  push: 
    branches: main

jobs:
    job_1:
        name: Upload Artifact
        runs-on: ubuntu-latest
        steps:
          - name: "Create a Local file"
            run: echo "Creating this file with content and uploading as artifact file and then in other job it can be downloaded and used its content" > file.txt

          - uses: actions/upload-artifact@v4
            with: 
                name: file
                path: file.txt
                retention-days: 10

    job_2:
        name: Download Artifact
        runs-on: ubuntu-latest
        needs: job_1
        steps:
          - uses: actions/download-artifact@v4
            with: 
                name: file
          - name: Printing the file  content
            run: cat file.txt