name: 'GitHub Secret'

on: workflow_dispatch

jobs:
    secret_job:
        name: 'Github Secret'
        runs-on: ubuntu-latest
        steps:
          - name: Print Secret
            run: |
                echo "APP_SECRET: ${{ secrets.MY_SECRET }}"
                echo "I don't have secret: ${{ secrets.FAKE_SECRET }}"

          - name: Print secret as an env var
            run: |
                echo "MY_SECRET: ${{ env.MY_SECRET}}"
            env: 
                MY_SECRET: ${{ secrets.MY_SECRET }}